# Generated by Django 4.0.2 on 2022-06-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainpage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
