# Generated by Django 4.0.6 on 2022-08-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='img',
            field=models.ImageField(upload_to='MainImages%Y%m'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='Pictures%Y%m'),
        ),
        migrations.AlterField(
            model_name='travelticket',
            name='small_content',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='travelticket',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
